package com.entity;

import java.util.Date;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.id
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.categoryId
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    private Integer categoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.titleIntro
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    private String titleintro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.content
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.md
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    private String md;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.createdtime
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    private Date createdtime;

    //
    private Category category;

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.id
     *
     * @return the value of blog.id
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.id
     *
     * @param id the value for blog.id
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.categoryId
     *
     * @return the value of blog.categoryId
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    public Integer getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.categoryId
     *
     * @param categoryid the value for blog.categoryId
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title
     *
     * @return the value of blog.title
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title
     *
     * @param title the value for blog.title
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.titleIntro
     *
     * @return the value of blog.titleIntro
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    public String getTitleintro() {
        return titleintro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.titleIntro
     *
     * @param titleintro the value for blog.titleIntro
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    public void setTitleintro(String titleintro) {
        this.titleintro = titleintro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.content
     *
     * @return the value of blog.content
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.content
     *
     * @param content the value for blog.content
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.md
     *
     * @return the value of blog.md
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    public String getMd() {
        return md;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.md
     *
     * @param md the value for blog.md
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    public void setMd(String md) {
        this.md = md;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.createdtime
     *
     * @return the value of blog.createdtime
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    public Date getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.createdtime
     *
     * @param createdtime the value for blog.createdtime
     *
     * @mbg.generated Mon Apr 15 00:46:13 CST 2019
     */
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }
}